server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 250MB

app:
  frontend-url: https://habidue.com

file:
  storage: s3

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${AWS_REGION}

logging:
  level:
    org.hibernate.SQL: warn
    com.habidue.app.service.notice.collector: info
    com.habidue.app.config.jwt.JwtAuthenticationEntryPoint: warn
